### ISSUE TITLE
Doesn't work with QAM?

### ISSUE THREAD

**Issue by Gatorfreak** [malahal/hdhomerun_recorder#2]
I think I have the mappings correct but when the job runs it creates a folder for the job and that's all.  Log file says the job ran successfully.  No error messages, yet no files generated.

I have my channel mapping as follows:

[channelmap]
# virtual-channel = physical-channel program-number ;name-of-program

1009 = qam256:110, 1 ;WNBW-DT
1013 = qam256:107, 103 ;WOGXHD

**Comment by malahal** [comment]
I never tested with QAM but based on what you said it is probably not
finding the binary (hdhomerun_config). Can you give absolute path to that
binary and make sure that it really works? It should actually get an
exception but that is something to try.

It should work with QAM as well, if you can't find the root cause of your
issue, I can provide a debug version to test out to get more details about
the issue.

Regards, Malahal.

**Comment by Gatorfreak** [comment]
Thanks for responding so quickly!  So sorry for being a dumbass user.  Indeed, it works with QAM if you have the path to the hdhomerun_config binary correct!  What a great app!
